#-----------------------
# customer.http
# 고객사 (화주) API 테스트
#-----------------------

### 1. customer 생성
POST /v1/customer
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "loginId": "customer092",
  "password": "test1234",
  "customerStatus": "ACTIVE",
  "customerGroup": "FINANCE",
  "name": "인삼공사",
  "phone": "01012345678",
  "memo": "고객사 메모",
  "email": "customer01@test.com"
}

### 2. customer 리스트 조회
GET /v1/customer?
Host: localhost:8080
Authorization: Bearer {{access_token}}

### 3. customer 상세 조회
#GET /v1/customer/{{customer_id}}
GET /v1/customer/7b59ae19-292e-4f2d-9c74-da3f4102b71c
Host: localhost:8080
Authorization: Bearer {{access_token}}

### 4. customer 수정
#PUT /v1/customer/{{customer_id}}
PUT /v1/customer/{{customer_id}}
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "customerGroup": "FINANCE",
  "name": "인삼공사",
  "email": "customer01@test.com",
  "phone": "01012345678",
  "memo": "고객사 메모 업데이트"
}

### 5. customer 삭제
#DELETE /v1/customer/{{customer_id}}
DELETE /v1/customer/{{customer_id}}
Host: localhost:8080
Authorization: Bearer {{access_token}}



