#-----------------------
# member.http
# 사용자 (실행사,택배사) API 테스트
#-----------------------

### 1. member 생성
POST /v1/member
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
   "customerId": "e1065afe-5d59-4293-b3f9-037d3122b8b6",
   "loginId": "member_02",
   "password": "test1234",
   "memberStatus": "ACTIVE",
   "memberType": "CLIENT",
   "managerName": "홍길동",
   "ceoName": "홍길동",
   "registrationNumber": "130-81-16025",
   "phone": "02-3400-5474",
   "memo": "고객메모",
   "email": "member_02@test.com"
}

### 2. member 리스트 조회 /v1/member?
#GET /v1/member?customerId=e1065afe-5d59-4293-b3f9-037d3122b8b6
GET /v1/member
Host: localhost:8080
Authorization: Bearer {{access_token}}

### 3. member 상세 조회
#GET /v1/member/{{member_id}}
GET /v1/member/be0403c8-6b43-41c3-bedc-0bd53dfc5977
Host: localhost:8080
Authorization: Bearer {{access_token}}

### 4. member 수정
#PUT /v1/member/{{member_id}}
PUT /v1/member/{{member_id}}
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "customerId": "7de5eb3f-fe59-453e-a0c1-f1f497ceee5c",
  "memberType": "EXECUTOR",
  "managerName": "홍길동",
  "ceoName": "홍길동",
  "registrationNumber": "130-81-16025",
  "phone": "02-3400-5474",
  "memo": "고객메모",
  "email": "string"
}

### 5. member 삭제
#DELETE /v1/member/{{member_id}}
DELETE /v1/member/{{member_id}}
Host: localhost:8080
Authorization: Bearer {{access_token}}



